### DISCUSSION TITLE
Blog Post [15]

### DISCUSSION THREAD

**Discussion by gordi76** [NicoReimer/Breakpoint#24] [Weekly-Blog]
# Blogeintrag – CI/CD Setup

## CI/CD Pipeline

Wir haben für unser Projekt eine CI/CD-Pipeline mit GitHub Actions eingerichtet. Die Konfigurationsdatei liegt unter `.github/workflows/ci.yml` und läuft bei jedem Push auf den `main`-Branch.

Die Pipeline enthält die folgenden Schritte:

- **Build:** Abhängigkeiten werden mit `npm ci` installiert.
- **Test:** Unit-Tests werden mit `npm test` ausgeführt.
- **(Optional) Deploy:** Aktuell kein Deployment, die Option bleibt offen.

## Konfiguration

**ci.yml (Ausschnitt):**
```yaml
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./reactApp/client
      - run: npm test -- --watchAll=false
        working-directory: ./reactApp/client
```

**dependabot.yml:**
```yaml
updates:
  - package-ecosystem: "npm"
    directory: "/reactApp/client"
    schedule:
      interval: "weekly"
```

## Aktueller Stand
- Die CI/CD-Konfiguration wurde erfolgreich ins Repository integriert.
- Die Testpipeline läuft wie gewünscht bei jedem Push auf main.
- Dependabot ist für automatische Dependency-Updates aktiv.
- Aktuell noch kein automatisiertes Deployment – geplant ist eine einfache Testumgebung.
